dailyfresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('df_user.urls')),
    path('', include('df_goods.urls')),
    path('cart/', include('df_cart.urls')),
    path('order/', include('df_order.urls')),
    path('tinymce/', include('tinymce.urls')),
    #path('search/',include('haystack.urls')),
]

df_cart/urls.py
#coding = utf-8
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.cart),
    re_path(r'^add(\d+)_(\d+)/$', views.add),
    re_path(r'^edit(\d+)_(\d+)/$', views.edit),
    re_path(r'^delete(\d+)/$', views.delete),
]

df_user/urls.py
#coding = utf-8
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^register/$', views.register),
    re_path(r'^register_handle/$', views.register_handle),
    re_path(r'^register_exist/$', views.register_exist),
    re_path(r'^login/$', views.login),
    re_path(r'^login_handle/$', views.login_handle),
    re_path(r'^logout/$', views.logout),
    re_path(r'^info/$', views.info),
    re_path(r'^order/(\d+)$', views.order),
    re_path(r'^site/$', views.site),
]

df_order/models.py
#coding=utf-8
from django.db import models

# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey('df_user.UserInfo',on_delete='models.CASCADE')
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.BooleanField(default=False)
    ototal = models.DecimalField(max_digits=6, decimal_places=2)
    oreceive = models.CharField(max_length=20, default='', )
    oaddress = models.CharField(max_length=100, default='', )
    opostcode = models.CharField(max_length=6, default='', )
    ophone = models.CharField(max_length=11, default='', )


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo',on_delete='models.CASCADE')
    order = models.ForeignKey(OrderInfo,on_delete='models.CASCADE')
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

df_user/models.py
#coding = utf-8
from django.db import models

# Create your models here.
class UserInfo(models.Model):
     uname = models.CharField(max_length=20)
     upwd = models.CharField(max_length=40)
     uemail = models.CharField(max_length=30)
     ureceive = models.CharField(max_length=20, default='',)
     uaddress = models.CharField(max_length=100, default='',)
     upostcode = models.CharField(max_length=6, default='',)
     uphone = models.CharField(max_length=11, default='',)
     #default与blank是python层面的约束，不影响数据库结构，不需要数据库迁移
     def __str__(self):
          # return self.ttitle.encode('utf-8')(python3不能这么写)
          return self.uname

df_user/views.py
#coding = utf-8
import django.core.paginator
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

import df_order.models
from .models import *
from hashlib import sha1
from . import user_decorator
from df_goods.models import GoodsInfo
from df_order.models import OrderInfo
from django.core.paginator import Paginator
# Create your views here.


def register(request):
    con = {'title': '用户注册',}
    return render(request, 'df_user/register.html', con)


def register_handle(request):
    #接收用户输入
    post = request.POST
    uname =post.get("user_name")
    upwd = post.get("pwd")
    upwd2 = post.get("cpwd")
    uemail = post.get("email")
    #判断两次密码
    if upwd != upwd2:
        return redirect('/user/register/')
    #密码加密
    s1 = sha1()
    s1.update(upwd.encode("utf8"))
    upw3 = s1.hexdigest()
    #创建实例
    user = UserInfo()
    user.uname = uname
    user.upwd = upw3
    user.uemail = uemail
    user.save()
    #注册成功转到登陆页面
    return redirect('/user/login/')


def register_exist(request):
    get = request.GET
    uname = get.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count': count})


def login(request):
    uname = request.COOKIES.get('uname', '')
    con = {'title': '用户登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname, }
    return render(request, 'df_user/login.html', context=con)


def login_handle(request):
    #接受请求
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    remember = post.get("remember", 0)
    #根据用户名查找对象
    users = UserInfo.objects.filter(uname=uname) #使用filter方法，uname不存在返回[]
    #判断：如果未查到则用户名错，如果查到则判断密码是否错误，正确则返回用户中心
    if len(users) == 1:
        s1 = sha1()
        s1.update(upwd.encode("utf8"))
        if s1.hexdigest() == users[0].upwd:
            rtd = HttpResponseRedirect('/user/info/')
            if remember != 0:
                rtd.set_cookie('uname', uname)
            else:
                rtd.set_cookie('uname', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return rtd
        else:
            con = {'title': '用户登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd, }
            return render(request, 'df_user/login.html', context=con)
    else:
        con = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd, }
        return render(request, 'df_user/login.html',context=con )


def logout(request):
    data = {}
    try:
        request.session.flush()
        data = {'ok':1}
    except Exception as e:
        pass
    #return redirect('/')
    return JsonResponse(data)


@user_decorator.login
def info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail
    user_address = UserInfo.objects.get(id=request.session['user_id']).uaddress
    #从cookies中读取goods_ids，并查询数据库中对应的goods
    goods_ids = request.COOKIES.get('goods_ids','')
    goods_idl = goods_ids.split(',')
    #GoodsInfo.objects.filter(id__in == goods_idl) #查询出来的是按id排序的
    goods_list = []
    if goods_ids != '':
        for goods_id in goods_idl:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    con = {'title': '用户中心', 'user_email': user_email,
           'user_name': request.session['user_name'],
           'user_address': user_address,
           'page_name': 1,
           'goods_list': goods_list, }
    return render(request, 'df_user/user_center_info.html',con)


@user_decorator.login
def order(request,index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    con = {'title': '用户中心', 'page_name': 1,
           'paginator': paginator,
           'page': page,}
    return render(request, 'df_user/user_center_order.html',con)


@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method=='POST':
        post = request.POST
        user.ureceive = post.get('ureceive')
        user.uaddress = post.get('uaddress')
        user.upostcode = post.get('upostcode')
        user.uphone = post.get('uphone')
        user.save()
    con = {'title': '用户中心','user': user, 'page_name': 1,}
    return render(request, 'df_user/user_center_site.html',con)

templates/df_user/login.html
{%extends 'base_foot.html'%}


{%block head%}
    <script>
        var error_name = {{error_name}};
        var error_pwd = {{error_pwd}};
    </script>
	<script type="text/javascript" src="/static/js/login.js"></script>
{%endblock head%}


{%block body%}
	<div class="login_top clearfix">
		<a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">{%csrf_token%}
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{upwd}}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{%endblock body%}

templates/df_user/register.html
{%extends 'base_foot.html'%}


{%block head%}
	<script type="text/javascript" src="/static/js/register.js"></script>
{%endblock head%}


{%block body%}
	<div class="register_con">
		<div class="l_con fl">
            <a href="/" class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" method="post">{%csrf_token%}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{%endblock body%}

templates/df_user/user_center_info.html
{%extends 'base.html'%}


{%block body%}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/order/1">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系方式：</span>{{user_email}}</li>
							<li><span>联系地址：</span>{{user_address}}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {%for g in goods_list%}
				        <li>
					        <a href="/{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
					        <h4><a href="{{g.id}}">{{g.gtitle}}</a></h4>
					        <div class="operate">
						        <span class="prize">￥{{g.gprice}}</span>
						        <span class="unit">{{g.gunit}}</span>
						        <a href="#" class="add_goods" title="加入购物车"></a>
					        </div>
				        </li>
                        {%endfor%}
                    </ul>
		        </div>
		</div>
	</div>
{%endblock body%}

templates/df_user/user_center_order.html
{%extends 'base.html'%}



{% block head %}

{% endblock %}

{%block body%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">订单号：{{ orderinfo.oid}}</li>
					<li class="col02 stress">已支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                            {%for order_detail in orderinfo.orderdetailinfo_set.all%}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{order_detail.goods.gpic}}"></li>
									<li class="col02" >{{order_detail.goods.gtitle}}<em>{{order_detail.goods.gprice}}元/{{order_detail.goods.gunit}}</em></li>
									<li class="col03">数量：{{order_detail.count}}</li>
									<li class="col04"></li>
								</ul>
                            {%endfor%}
							</td>
							<td width="15%">总计：{{ orderinfo.ototal }}元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>
					</tbody>
				</table>
            {% endfor %}

			<div class="pagenation">
                {%if page.has_previous%}
				<a href="/user/order/{{page.previous_page_number}}">上一页</a>
                {%endif%}

                {%for pindex in paginator.page_range%}
                {%if pindex == page.number%}
                    <a href="/user/order/{{pindex}}" class="active">{{pindex}}</a>
                {%else%}
                    <a href="/user/order/{{pindex}}">{{pindex}}</a>
                {%endif%}
                {%endfor%}

                {%if page.has_next%}
				<a href="/user/order/{{page.next_page_number}}">下一页</a>
                {%endif%}
			</div>
		</div>
	</div>
{%endblock body%}

templates/df_user/user_center_site.html
{%extends 'base.html'%}


{%block body%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/order/1">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} （{{user.ureceive}} 收） {{user.uphone}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ureceive" value="{{ user.ureceive }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="upostcode" value="{{ user.upostcode }}" >
						</div>
						<div class="form_group" >
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ user.uphone }}">
						</div>

						<input type="submit" name="" value="修改地址" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{%endblock body%}